backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "data"
    label: "Məlumatlar"
    files:
      - name: "products"
        label: "Məhsullar"
        file: "data/products.json"
        format: "json"
        fields:
          - label: "Məhsullar"
            name: "products"
            widget: "list"
            fields:
              - label: "Məhsul adı"
                name: "name"
                widget: "string"
              - label: "Açıqlama"
                name: "description"
                widget: "text"
              - label: "Şəkil"
                name: "image"
                widget: "image"
