backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Məhsullar"
    file: "data/products.json"
    format: "json"
    fields:
      - { label: "Ad", name: "name", widget: "string" }
      - { label: "Açıqlama", name: "description", widget: "string" }
      - { label: "Şəkil", name: "image", widget: "image" }
